name: Build and Test
on:
  push:
    branches:
    - master
jobs:
  runner:
    name: Package Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Build Solution
        run:  dotnet build -c Release
      - name: Test Solution
        run:  dotnet test
      - name: Deploy Solution
        run:  dotnet nuget push ./Alexa.NET.Gadgets/bin/release/Alexa.NET*.nupkg -k {{ secrets.NUGET_KEY }}
